-- Workspaces, their members and invitations.
--
-- Generated by Prisma, then edited by hand in two places, both marked below.

-- CreateEnum
CREATE TYPE "WorkspaceBusinessType" AS ENUM ('INDIVIDUAL_AGENT', 'BROKERAGE', 'CHANNEL_PARTNER', 'DEVELOPER', 'OTHER');

-- Hand-written, replacing Prisma's AlterEnum steps.
--
-- Both types were reserved by the init migration and never used by a column,
-- so they are recreated rather than altered. Prisma's generated steps failed
-- on both: its InvitationStatus rebuild altered workspace_invitations before
-- the table exists, and a value added with ADD VALUE cannot be used in the
-- transaction that adds it — the workspaces default below uses it. ADD VALUE
-- would also have appended PENDING_APPROVAL rather than placed it first.
DROP TYPE "WorkspaceStatus";
CREATE TYPE "WorkspaceStatus" AS ENUM ('PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED', 'ARCHIVED', 'REJECTED');

DROP TYPE "InvitationStatus";
CREATE TYPE "InvitationStatus" AS ENUM ('PENDING', 'ACCEPTED', 'DECLINED', 'REVOKED', 'EXPIRED');

-- DropEnum
DROP TYPE "RoleSource";

-- CreateTable
CREATE TABLE "workspaces" (
    "id" UUID NOT NULL DEFAULT uuidv7(),
    "name" VARCHAR(150) NOT NULL,
    "slug" VARCHAR(60) NOT NULL,
    "business_type" "WorkspaceBusinessType" NOT NULL,
    "status" "WorkspaceStatus" NOT NULL DEFAULT 'PENDING_APPROVAL',
    "owner_user_id" UUID NOT NULL,
    "country_code" CHAR(2) NOT NULL,
    "timezone" VARCHAR(64) NOT NULL,
    "currency" CHAR(3) NOT NULL,
    "rera_number" VARCHAR(50),
    "onboarding_completed_at" TIMESTAMPTZ(6),
    "reviewed_at" TIMESTAMPTZ(6),
    "reviewed_by_admin_id" UUID,
    "review_note" VARCHAR(500),
    "suspended_at" TIMESTAMPTZ(6),
    "archived_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "workspaces_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "workspace_members" (
    "id" UUID NOT NULL DEFAULT uuidv7(),
    "workspace_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "status" "MembershipStatus" NOT NULL DEFAULT 'ACTIVE',
    "job_title" VARCHAR(100),
    "invited_by_user_id" UUID,
    "joined_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status_changed_at" TIMESTAMPTZ(6),
    "status_changed_by_user_id" UUID,
    "last_accessed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "workspace_members_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "workspace_invitations" (
    "id" UUID NOT NULL DEFAULT uuidv7(),
    "workspace_id" UUID NOT NULL,
    "email" VARCHAR(320) NOT NULL,
    "token_hash" VARCHAR(64) NOT NULL,
    "status" "InvitationStatus" NOT NULL DEFAULT 'PENDING',
    "invited_by_user_id" UUID,
    "accepted_by_user_id" UUID,
    "send_count" INTEGER NOT NULL DEFAULT 1,
    "last_sent_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolved_at" TIMESTAMPTZ(6),
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "workspace_invitations_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "workspaces_slug_key" ON "workspaces"("slug");

-- CreateIndex
CREATE INDEX "workspaces_owner_user_id_idx" ON "workspaces"("owner_user_id");

-- CreateIndex
CREATE INDEX "workspaces_status_created_at_idx" ON "workspaces"("status", "created_at");

-- CreateIndex
CREATE INDEX "workspace_members_user_id_status_idx" ON "workspace_members"("user_id", "status");

-- CreateIndex
CREATE INDEX "workspace_members_workspace_id_status_idx" ON "workspace_members"("workspace_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "workspace_members_workspace_id_user_id_key" ON "workspace_members"("workspace_id", "user_id");

-- CreateIndex
CREATE UNIQUE INDEX "workspace_members_workspace_id_id_key" ON "workspace_members"("workspace_id", "id");

-- CreateIndex
CREATE UNIQUE INDEX "workspace_invitations_token_hash_key" ON "workspace_invitations"("token_hash");

-- CreateIndex
CREATE INDEX "workspace_invitations_email_status_idx" ON "workspace_invitations"("email", "status");

-- CreateIndex
CREATE INDEX "workspace_invitations_workspace_id_status_created_at_idx" ON "workspace_invitations"("workspace_id", "status", "created_at" DESC);

-- AddForeignKey
ALTER TABLE "workspaces" ADD CONSTRAINT "workspaces_owner_user_id_fkey" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspaces" ADD CONSTRAINT "workspaces_reviewed_by_admin_id_fkey" FOREIGN KEY ("reviewed_by_admin_id") REFERENCES "admins"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspace_members" ADD CONSTRAINT "workspace_members_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspace_members" ADD CONSTRAINT "workspace_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspace_members" ADD CONSTRAINT "workspace_members_invited_by_user_id_fkey" FOREIGN KEY ("invited_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspace_members" ADD CONSTRAINT "workspace_members_status_changed_by_user_id_fkey" FOREIGN KEY ("status_changed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspace_invitations" ADD CONSTRAINT "workspace_invitations_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspace_invitations" ADD CONSTRAINT "workspace_invitations_invited_by_user_id_fkey" FOREIGN KEY ("invited_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspace_invitations" ADD CONSTRAINT "workspace_invitations_accepted_by_user_id_fkey" FOREIGN KEY ("accepted_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Hand-written: not expressible in schema.prisma (see the model comments).

-- One workspace awaiting review per owner: a signup cannot queue a hundred.
CREATE UNIQUE INDEX "workspaces_one_pending_per_owner_key"
    ON "workspaces" ("owner_user_id")
    WHERE "status" = 'PENDING_APPROVAL';

-- One pending invitation per address per workspace; a resolved one does not
-- block a new invitation.
CREATE UNIQUE INDEX "workspace_invitations_pending_key"
    ON "workspace_invitations" ("workspace_id", "email")
    WHERE "status" = 'PENDING';

-- The expiry sweep reads pending rows only.
CREATE INDEX "workspace_invitations_expiry_idx"
    ON "workspace_invitations" ("expires_at")
    WHERE "status" = 'PENDING';

-- Each status timestamp exists exactly while its status holds. Review is
-- one-sided: a workspace that never needed review is ACTIVE with none.
ALTER TABLE "workspaces"
    ADD CONSTRAINT "chk_workspaces_suspended"
        CHECK (("status" = 'SUSPENDED') = ("suspended_at" IS NOT NULL)),
    ADD CONSTRAINT "chk_workspaces_archived"
        CHECK (("status" = 'ARCHIVED') = ("archived_at" IS NOT NULL)),
    ADD CONSTRAINT "chk_workspaces_reviewed"
        CHECK (("status" <> 'PENDING_APPROVAL' OR "reviewed_at" IS NULL)
           AND ("status" <> 'REJECTED' OR "reviewed_at" IS NOT NULL));

-- Only a member active since creation has no status change recorded.
ALTER TABLE "workspace_members"
    ADD CONSTRAINT "chk_workspace_members_status_changed"
        CHECK ("status" = 'ACTIVE' OR "status_changed_at" IS NOT NULL);

-- An invitation is resolved exactly when it has left PENDING.
ALTER TABLE "workspace_invitations"
    ADD CONSTRAINT "chk_workspace_invitations_resolved"
        CHECK (("status" = 'PENDING') = ("resolved_at" IS NULL));
