export const EMAIL_TRANSPORT_LOG_CONTEXT = 'EmailTransport';

export const EMAIL_ORIGINAL_TO_HEADER = 'X-Original-To';

export const EMAIL_TRANSPORT_ERROR_CODE = {
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  INVALID_SENDER: 'INVALID_SENDER',
  INVALID_RECIPIENT: 'INVALID_RECIPIENT',
  MESSAGE_REJECTED: 'MESSAGE_REJECTED',
  RATE_LIMITED: 'RATE_LIMITED',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  TIMEOUT: 'TIMEOUT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type EmailTransportErrorCode =
  (typeof EMAIL_TRANSPORT_ERROR_CODE)[keyof typeof EMAIL_TRANSPORT_ERROR_CODE];

export const RETRYABLE_EMAIL_TRANSPORT_ERROR_CODES: ReadonlySet<EmailTransportErrorCode> = new Set([
  EMAIL_TRANSPORT_ERROR_CODE.RATE_LIMITED,
  EMAIL_TRANSPORT_ERROR_CODE.PROVIDER_UNAVAILABLE,
  EMAIL_TRANSPORT_ERROR_CODE.TIMEOUT,
]);
