export const REDIS_DEFAULTS = {
  CONNECT_TIMEOUT_MS: 5_000,

  COMMAND_TIMEOUT_MS: 3_000,

  MAX_RETRIES_PER_REQUEST: 3,

  RECONNECT_MAX_ATTEMPTS: 0,
  RECONNECT_BASE_DELAY_MS: 200,
  RECONNECT_MAX_DELAY_MS: 5_000,
} as const;

export const REDIS_RECONNECT_UNLIMITED = 0;

export const REDIS_KEY_PREFIX_PATTERN = /^[^{}]*$/;

export const REDIS_KEY_SEPARATOR = ':';
