export const VERIFICATION_LOG_CONTEXT = 'Verification';

export const VERIFICATION_CODE_PATTERN = /^\d{6}$/;

export const VERIFICATION_CODE_TTL_MS = 10 * 60 * 1000;

export const VERIFICATION_CODE_TTL_MINUTES = VERIFICATION_CODE_TTL_MS / 60_000;

export const VERIFICATION_CODE_MAX_ATTEMPTS = 5;

export const VERIFICATION_CODE_MIN_RESEND_INTERVAL_MS = 30 * 1000;
