import { HttpStatus } from '@nestjs/common';

import { EXCEPTION_CODE, type ExceptionCode } from '../constants/exception.constants.js';

/**
 * Maps NestJS HTTP status codes
 * to application error codes.
 *
 * Single source of truth.
 */
const HTTP_STATUS_TO_ERROR_CODE = new Map<HttpStatus, ExceptionCode>([
  [HttpStatus.BAD_REQUEST, EXCEPTION_CODE.BAD_REQUEST],
  [HttpStatus.UNAUTHORIZED, EXCEPTION_CODE.UNAUTHORIZED],
  [HttpStatus.FORBIDDEN, EXCEPTION_CODE.FORBIDDEN],
  [HttpStatus.NOT_FOUND, EXCEPTION_CODE.NOT_FOUND],
  [HttpStatus.METHOD_NOT_ALLOWED, EXCEPTION_CODE.METHOD_NOT_ALLOWED],
  [HttpStatus.NOT_ACCEPTABLE, EXCEPTION_CODE.BAD_REQUEST],
  [HttpStatus.REQUEST_TIMEOUT, EXCEPTION_CODE.BAD_REQUEST],
  [HttpStatus.CONFLICT, EXCEPTION_CODE.CONFLICT],
  [HttpStatus.GONE, EXCEPTION_CODE.NOT_FOUND],
  [HttpStatus.PAYLOAD_TOO_LARGE, EXCEPTION_CODE.BAD_REQUEST],
  [HttpStatus.UNSUPPORTED_MEDIA_TYPE, EXCEPTION_CODE.BAD_REQUEST],
  [HttpStatus.UNPROCESSABLE_ENTITY, EXCEPTION_CODE.UNPROCESSABLE_ENTITY],
  [HttpStatus.TOO_MANY_REQUESTS, EXCEPTION_CODE.TOO_MANY_REQUESTS],
  [HttpStatus.INTERNAL_SERVER_ERROR, EXCEPTION_CODE.INTERNAL_SERVER_ERROR],
  [HttpStatus.NOT_IMPLEMENTED, EXCEPTION_CODE.INTERNAL_SERVER_ERROR],
  [HttpStatus.BAD_GATEWAY, EXCEPTION_CODE.SERVICE_UNAVAILABLE],
  [HttpStatus.SERVICE_UNAVAILABLE, EXCEPTION_CODE.SERVICE_UNAVAILABLE],
  [HttpStatus.GATEWAY_TIMEOUT, EXCEPTION_CODE.GATEWAY_TIMEOUT],
]);
export abstract class ExceptionCodeMapper {
  static map(status: HttpStatus): ExceptionCode {
    return HTTP_STATUS_TO_ERROR_CODE.get(status) ?? EXCEPTION_CODE.INTERNAL_SERVER_ERROR;
  }
}
