import type { FastifyCorsOptions } from '@fastify/cors';

import {
  CONTENT_DISPOSITION_HEADER,
  CORRELATION_ID_HEADER,
  DEVICE_ID_HEADER,
  RATE_LIMIT_HEADER,
  REQUEST_ID_HEADER,
  RESPONSE_REQUEST_ID_HEADER,
  RETRY_AFTER_HEADER,
  TIMEZONE_HEADER,
  WORKSPACE_ID_HEADER,
} from '#/shared/constants/index.js';

const PREFLIGHT_MAX_AGE_SECONDS = 600;

const ALLOWED_REQUEST_HEADERS = [
  'Content-Type',
  'Authorization',

  DEVICE_ID_HEADER,

  WORKSPACE_ID_HEADER,

  TIMEZONE_HEADER,

  REQUEST_ID_HEADER,
  CORRELATION_ID_HEADER,
];

const EXPOSED_RESPONSE_HEADERS = [
  RESPONSE_REQUEST_ID_HEADER,

  RATE_LIMIT_HEADER.LIMIT,
  RATE_LIMIT_HEADER.REMAINING,
  RATE_LIMIT_HEADER.RESET,
  RETRY_AFTER_HEADER,
  CONTENT_DISPOSITION_HEADER,
];

export const DEFAULT_CORS_OPTIONS: Pick<
  FastifyCorsOptions,
  'methods' | 'allowedHeaders' | 'exposedHeaders' | 'maxAge'
> = {
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],

  allowedHeaders: ALLOWED_REQUEST_HEADERS,

  exposedHeaders: EXPOSED_RESPONSE_HEADERS,

  maxAge: PREFLIGHT_MAX_AGE_SECONDS,
};
